### PR TITLE
TST: try standard pcds build test

### PR DESCRIPTION
**Pull request by tangkong**
## Description
- adds basic conda and pip build tests based on pcds-ci-helpers
- Adjusts C code to be numpy2 compatible
- Adjusts pip build recipe to more closely resemble the conda-forge recipe
  - uses epicscorelibs for epics library headers
  - use setuptools_dso for extension building

## Context
We want to get the pcds ecosystem set up to work with numpy 2.0, and the build system for this package has been outdated for a while.

Currently pip builds and tests are passing, but the conda recipe needs some looking at.

## testing 
Actions will not show up until this is approved and merged, but they are running on my fork currently:
https://github.com/tangkong/pyca/actions

### CODE REVIEW

**Comment by tangkong** [comment]
I think this is a reasonable place to stop.  pip builds are working and the conda builds will require a fight with conda-forge in the near future anyway, so this will be revisited then.

File: pyca/getfunctions.hh [hunk 1]
```diff
@@ -107,7 +108,8 @@ PyObject* _pyca_get_value(capv* pv, const T* dbrv, long count)
         npy_intp dims[1] = {count};
         int typenum = _numpy_array_type(&(dbrv->value));
         PyObject* nparray = PyArray_EMPTY(1, dims, typenum, 0);
-        memcpy(PyArray_DATA(nparray), &(dbrv->value), count*sizeof(dbrv->value));
+        PyArrayObject *arr = (PyArrayObject *)PyArray_FROM_O(nparray);
```
Comment (tangkong) [inline pyca/getfunctions.hh:111]: Some notes for the reviewer:  [PyArray_DATA](https://numpy.org/doc/stable/reference/c-api/array.html#c.PyArray_DATA) expects to take a `PyArrayObject` as its argument.  This wasn't explicitly called out in the[ numpy2.0 migration guide](https://numpy.org/doc/stable/numpy_2_0_migration_guide.html), but was causing compilation errors.

File: pyca/putfunctions.hh [hunk 2]
```diff
@@ -60,13 +60,16 @@ void _pyca_put_value(capv* pv, PyObject* pyvalue, T** buf, long count)
...
         PyObject* pyval = PyTuple_GetItem(pyvalue, 0);
         _pyca_put(pyval, buffer);
       } else if (PyArray_Check(pyvalue)) {
-        void* npdata = PyArray_GETPTR1(pyvalue, 0);
+        // Convert to array
+        PyArrayObject *arr = (PyArrayObject *)PyArray_FROM_O(pyvalue); 
+        char* npdata = static_cast<char*>(PyArray_GETPTR1(arr, 0));
         if (PyArray_IsPythonScalar(pyvalue)) {
-          PyObject* pyval = PyArray_GETITEM(pyvalue, npdata);
+          PyObject* pyval = PyArray_GETITEM(arr, npdata);
```
Comment (tangkong) [inline pyca/putfunctions.hh:72]: Note for the reviewer:  This change revolves around casting `npdata` to a `char*`, despite the numpy docs insisting that `PyArray_GETITEM` takes a `void*` as its second argument ([api docs](https://numpy.org/doc/stable/reference/c-api/array.html#c.PyArray_GETITEM)).  

This was, of course, changed in reaction to compilation errors.  These errors could be downgraded to warnings if `-fpermissive` was specified as a compiler arg, but other source code sources seemed to corroborate this slightly more specific signature [numpy/_core/include/numpy/ndarrayobject.h](https://github.com/numpy/numpy/blob/1af7cb3c2d42800a5614baef5b5fdadad808e4c4/numpy/_core/include/numpy/ndarrayobject.h#L279-L284)

Comment (tangkong) [reply pyca/putfunctions.hh:72]: The linked function then take the `char*` and casts it to a `void*`, but I'm not digging any further into this...

**Comment by ZLLentz** [comment]
I'm on board with all the changes
Perhaps afterwards we should tag with the intent of getting out conda builds with wider dependency maps

Before approving I'm going to clone this and try it out where I can

**Comment by tangkong** [comment]
Tagging was my intention 👍 I'm not feeling like getting the conda builds working right now, anyway

**Comment by ZLLentz** [comment]
Works like a charm interactively, I'm trying something a little harder (seeing if it works with camviewer) and am mostly stumbling on env setup. After that I'll hit approve (even if it doesn't work, it's just something else to do before tagging)

**Review by ZLLentz — APPROVED** [review]
Let's get this in

camviewer was a fool's errand for miscellaneous reasons
